FROM nickblah/lua:5.3.5-luarocks-alpine

ENV PORT 8080

WORKDIR /app

RUN apk --no-cache add \
  openssl \
  && apk --no-cache add --virtual build-deps \
  bsd-compat-headers \
  build-base \
  m4 \
  cmake \
  git \
  unzip \
  openssl-dev \
  && luarocks install lua-cjson 2.1.0 \
  && luarocks install http \
  && apk del build-deps

ADD src ./
ADD test ./

CMD ["lua", "test_routes.lua"]
