name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: lua test/test_routes.lua
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build and register image
        uses: actions-hub/gcloud@268.0.0
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: builds submit --tag gcr.io/${{secrets.GCLOUD_PROJECT_ID}}/luahttp:${{steps.extract_branch.outputs.branch}}
      - name: Deploy to cloud run
        uses: actions-hub/gcloud@268.0.0
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: components install beta && gcloud beta run services add-iam-policy-binding --region=us-east1 --member=allUsers --role=roles/run.invoker cnluapoc-${{steps.extract_branch.outputs.branch}} && gcloud beta run deploy cnluapoc-${{steps.extract_branch.outputs.branch}} --quiet --platform managed --region us-east1 --allow-unauthenticated --image gcr.io/${{secrets.GCLOUD_PROJECT_ID}}/luahttp:${{steps.extract_branch.outputs.branch}}
